plugins {
    id 'dev.hybridlabs.fabric'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    modApi "software.bernie.geckolib:geckolib-fabric-$geckolib_version"
}

fabricApi {
    configureDataGeneration {
        outputDirectory = file("src/generated/resources")
        client = true
    }
}

publishMods.platforms.configureEach {
    requires 'fabric-api', 'fabric-language-kotlin', 'geckolib'
}
